#!/usr/bin/env bash
# =============================================================================
# PM Tools — One-command setup for humans and AI agents
#
# AI AGENTS: Run this script when a user asks you to "set this up":
#   ./setup.sh
#
# The script is safe to re-run (idempotent). It will:
#   1. Build the pm-tools-mcp binary from Go source
#   2. Create .env from the template (skip if already exists)
#   3. Update .claude/settings.json with the correct absolute path
#   4. Install the MCP server into Claude Desktop config (macOS / Linux)
#
# Flags:
#   --skip-env          Skip .env creation (credentials already in env vars)
#   --skip-desktop      Skip Claude Desktop config update
#   --non-interactive   Never prompt (fail if credentials are missing)
# =============================================================================
set -euo pipefail

# ─── Paths ───────────────────────────────────────────────────────────────────
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MCP_DIR="$ROOT/pm-skills/tooling/mcp"
MCP_SRC="$MCP_DIR/server.go"
MCP_BIN="$MCP_DIR/pm-tools-mcp"
SETTINGS="$ROOT/.claude/settings.json"
ENV_FILE="$ROOT/.env"
ENV_EXAMPLE="$ROOT/.env.example"

# ─── Flags ───────────────────────────────────────────────────────────────────
SKIP_ENV=false
SKIP_DESKTOP=false
NON_INTERACTIVE=false
for arg in "$@"; do
  case "$arg" in
    --skip-env)          SKIP_ENV=true ;;
    --skip-desktop)      SKIP_DESKTOP=true ;;
    --non-interactive)   NON_INTERACTIVE=true ;;
  esac
done

# ─── Helpers ─────────────────────────────────────────────────────────────────
info()  { echo "  [•] $*"; }
ok()    { echo "  [✓] $*"; }
warn()  { echo "  [!] $*" >&2; }
die()   { echo "  [✗] $*" >&2; exit 1; }

prompt() {
  local label="$1" var="$2" default="${3:-}"
  if $NON_INTERACTIVE; then
    [[ -z "${!var:-}" ]] && die "$var is required but not set (use --skip-env if credentials are in the environment)"
    return
  fi
  local current="${!var:-$default}"
  if [[ -n "$current" ]]; then
    read -rp "    $label [$current]: " input
    input="${input:-$current}"
  else
    read -rp "    $label: " input
  fi
  export "$var"="${input:-$current}"
}

# ─── Step 1: Build binary ────────────────────────────────────────────────────
echo ""
echo "=== Step 1: Build pm-tools-mcp ==="

if ! command -v go &>/dev/null; then
  die "Go is not installed. Install from https://go.dev/dl/ and re-run this script."
fi

GO_VERSION=$(go version | awk '{print $3}' | sed 's/go//')
info "Go $GO_VERSION found"

info "Building from $MCP_SRC ..."
(cd "$MCP_DIR" && go build -o pm-tools-mcp server.go)
ok "Binary built: $MCP_BIN"

# ─── Step 2: Create .env ────────────────────────────────────────────────────
echo ""
echo "=== Step 2: Credentials & Domain Configuration (.env) ==="

if $SKIP_ENV; then
  info "Skipping .env (--skip-env set)"
elif [[ -f "$ENV_FILE" ]]; then
  ok ".env already exists — skipping (delete it to reconfigure)"
else
  info "Creating .env from template..."

  if ! $NON_INTERACTIVE; then
    echo ""
    echo "  === Jira & Confluence Credentials ==="
    echo "  Enter your credentials (press Enter to keep the default shown in [brackets])."
    echo "  Leave blank only if you do not use that service."
    echo ""
  fi

  JIRA_URL="${JIRA_URL:-}"
  JIRA_EMAIL="${JIRA_EMAIL:-}"
  JIRA_API_TOKEN="${JIRA_API_TOKEN:-}"
  CONFLUENCE_URL="${CONFLUENCE_URL:-}"
  CONFLUENCE_EMAIL="${CONFLUENCE_EMAIL:-}"
  CONFLUENCE_API_TOKEN="${CONFLUENCE_API_TOKEN:-}"
  DOMAIN_NAME="${DOMAIN_NAME:-}"
  JIRA_PROJECT_KEY="${JIRA_PROJECT_KEY:-}"
  CONFLUENCE_SPACES="${CONFLUENCE_SPACES:-}"

  prompt "Jira URL (e.g. https://jira.company.com)"      JIRA_URL
  prompt "Jira email"                                      JIRA_EMAIL
  prompt "Jira API token"                                  JIRA_API_TOKEN
  prompt "Confluence URL (e.g. https://wiki.company.com)" CONFLUENCE_URL
  prompt "Confluence email"                               CONFLUENCE_EMAIL
  prompt "Confluence API token"                           CONFLUENCE_API_TOKEN

  if ! $NON_INTERACTIVE; then
    echo ""
    echo "  === Domain Configuration ==="
    echo "  (These help tailor skills to your team's context)"
    echo ""
  fi

  prompt "Domain/Team name (e.g. Payment Core, Cross-border, FX Management)" DOMAIN_NAME "Payment Core"
  prompt "Jira project key (e.g. PCDPC, XB, FXM)"                            JIRA_PROJECT_KEY "PCDPC"
  prompt "Confluence spaces (comma-separated keys, e.g. PAYMENTS,ENGINE)"    CONFLUENCE_SPACES "PAYMENTS"

  cat > "$ENV_FILE" <<EOF
# Generated by setup.sh — edit freely

# ─── Jira & Confluence Credentials ─────────────────────
JIRA_URL=${JIRA_URL}
JIRA_EMAIL=${JIRA_EMAIL}
JIRA_API_TOKEN=${JIRA_API_TOKEN}
CONFLUENCE_URL=${CONFLUENCE_URL}
CONFLUENCE_EMAIL=${CONFLUENCE_EMAIL}
CONFLUENCE_API_TOKEN=${CONFLUENCE_API_TOKEN}

# ─── Domain Configuration ──────────────────────────────
# Used by PM skills to tailor context and examples
DOMAIN_NAME=${DOMAIN_NAME}
JIRA_PROJECT_KEY=${JIRA_PROJECT_KEY}
CONFLUENCE_SPACES=${CONFLUENCE_SPACES}

# Optional: Web fetcher settings
# WEB_USER_AGENT="Custom Bot 1.0"
# WEB_TIMEOUT=60
EOF
  ok ".env created"
fi

# ─── Step 3: Update .claude/settings.json ────────────────────────────────────
echo ""
echo "=== Step 3: Claude Code config (.claude/settings.json) ==="

if [[ ! -f "$SETTINGS" ]]; then
  warn "settings.json not found — creating a minimal one"
  mkdir -p "$ROOT/.claude"
  cat > "$SETTINGS" <<'EOJSON'
{
  "mcpServers": {}
}
EOJSON
fi

# Use Python (always available on macOS/Linux) to update the JSON safely
python3 - "$SETTINGS" "$MCP_BIN" <<'PYEOF'
import json, sys

settings_path = sys.argv[1]
mcp_bin = sys.argv[2]

with open(settings_path) as f:
    cfg = json.load(f)

cfg.setdefault("mcpServers", {})
cfg["mcpServers"]["pm-tools"] = {
    "command": mcp_bin,
    "env": {
        "JIRA_URL": "${JIRA_URL}",
        "JIRA_API_TOKEN": "${JIRA_API_TOKEN}",
        "CONFLUENCE_URL": "${CONFLUENCE_URL}",
        "CONFLUENCE_EMAIL": "${CONFLUENCE_EMAIL}",
        "CONFLUENCE_API_TOKEN": "${CONFLUENCE_API_TOKEN}"
    }
}

with open(settings_path, "w") as f:
    json.dump(cfg, f, indent=2)
    f.write("\n")

print(f"  [✓] pm-tools MCP registered at {mcp_bin}")
PYEOF

# ─── Step 4: Claude Desktop config ───────────────────────────────────────────
echo ""
echo "=== Step 4: Claude Desktop config ==="

if $SKIP_DESKTOP; then
  info "Skipping Claude Desktop (--skip-desktop set)"
else
  # Detect config location
  if [[ "$OSTYPE" == "darwin"* ]]; then
    DESKTOP_CFG="$HOME/Library/Application Support/Claude/claude_desktop_config.json"
  elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    DESKTOP_CFG="${XDG_CONFIG_HOME:-$HOME/.config}/Claude/claude_desktop_config.json"
  else
    warn "Claude Desktop config location unknown on this OS — skip with --skip-desktop"
    DESKTOP_CFG=""
  fi

  if [[ -n "$DESKTOP_CFG" ]]; then
    mkdir -p "$(dirname "$DESKTOP_CFG")"

    python3 - "$DESKTOP_CFG" "$MCP_BIN" "$ENV_FILE" <<'PYEOF'
import json, os, sys

cfg_path = sys.argv[1]
mcp_bin  = sys.argv[2]
env_file = sys.argv[3]

# Load existing config or start fresh
if os.path.exists(cfg_path):
    with open(cfg_path) as f:
        try:
            cfg = json.load(f)
        except json.JSONDecodeError:
            cfg = {}
else:
    cfg = {}

cfg.setdefault("mcpServers", {})
# PM_TOOLS_ENV_FILE tells the binary exactly where to load credentials from.
# Claude Desktop does NOT expand ${VAR} in env — so we pass the .env path
# instead of raw variable references. The binary loads the file at startup.
cfg["mcpServers"]["pm-tools"] = {
    "command": mcp_bin,
    "env": {
        "PM_TOOLS_ENV_FILE": env_file
    }
}

with open(cfg_path, "w") as f:
    json.dump(cfg, f, indent=2)
    f.write("\n")

print(f"  [✓] Claude Desktop config updated: {cfg_path}")
PYEOF
  fi
fi

# ─── Verify ──────────────────────────────────────────────────────────────────
echo ""
echo "=== Verifying MCP server ==="
TOOLS=$(printf '{"jsonrpc":"2.0","id":1,"method":"initialize","params":{}}\n{"jsonrpc":"2.0","id":2,"method":"tools/list","params":{}}\n' \
  | "$MCP_BIN" 2>/dev/null \
  | python3 -c "
import sys, json
lines = sys.stdin.read().strip().split('\n')
for line in lines:
    try:
        resp = json.loads(line)
        if resp.get('id') == 2:
            tools = resp['result']['tools']
            print(', '.join(t['name'] for t in tools))
    except: pass
" 2>/dev/null || true)

if [[ -n "$TOOLS" ]]; then
  ok "MCP server responds correctly"
  info "Tools available: $TOOLS"
else
  warn "Could not verify MCP server — check binary manually: $MCP_BIN"
fi

# ─── Done ────────────────────────────────────────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Setup complete!"
echo ""
echo "  • Claude Code: restart the session — pm-tools MCP is active"
echo "  • Claude Desktop: restart the app — pm-tools MCP will appear"
echo ""
echo "  Credentials: edit $ENV_FILE"
echo "  MCP binary:  $MCP_BIN"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
