package main

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"
)

// Requirement represents a feature or constraint extracted from a document
type Requirement struct {
	Category    string `json:"category"`
	Feature     string `json:"feature"`
	Description string `json:"description"`
}

// Capability represents an existing or planned system ability
type Capability struct {
	Component   string `json:"component"`
	Description string `json:"description"`
	Status      string `json:"status"` // e.g., Supported, Partially, Gap, Planned
}

// AnalysisResult maps a requirement to a capability and assesses feasibility
type AnalysisResult struct {
	Requirement Requirement `json:"requirement"`
	Feasibility string      `json:"feasibility"`
	Component   string      `json:"component"`
	Status      string      `json:"status"`
	Notes       string      `json:"notes"`
}

func main() {
	if len(os.Args) < 2 {
		fmt.Println("Usage: analyzer <requirements.json>")
		os.Exit(1)
	}

	// 1. Load Requirements from JSON
	reqData, err := os.ReadFile(os.Args[1])
	if err != nil {
		fmt.Printf("Error reading requirements: %v\n", err)
		os.Exit(1)
	}

	var requirements []Requirement
	if err := json.Unmarshal(reqData, &requirements); err != nil {
		fmt.Printf("Error parsing requirements: %v\n", err)
		os.Exit(1)
	}

	// 2. Define standard Payment Core Capabilities (could be moved to a config file)
	capabilities := map[string]Capability{
		"PE": {
			"Payment Engine",
			"Internal orders, IBFT, P2P transfers.",
			"Supported",
		},
		"FMC": {
			"Financial Management Center",
			"Merchant payments, fund movement, disbursement.",
			"Supported",
		},
		"Settlement": {
			"Settlement Component",
			"Merchant settlement and reconciliation.",
			"Partially",
		},
		"Order": {
			"Order Lifecycle",
			"Transaction state machine (V1/V2).",
			"Partially",
		},
		"Risk": {
			"Risk/Fraud Engine",
			"Fraud and AML scanning.",
			"Planned",
		},
		"Infra": {
			"Infrastructure",
			"Connectivity, sFTP, API Gateway.",
			"Supported",
		},
	}

	// 3. Perform Analysis
	fmt.Println("# FEASIBILITY ANALYSIS REPORT")
	fmt.Println("Generated by Technical Advisor PDF Tooling\n")
	fmt.Printf("%-30s | %-12s | %-12s | %-12s | %s\n", "Feature", "Feasibility", "Component", "Status", "Notes")
	fmt.Println(strings.Repeat("-", 120))

	for _, req := range requirements {
		feasibility := "High"
		compKey := "PE"

		// Logic for mapping categories to components (generic defaults)
		switch req.Category {
		case "Transfer":
			compKey = "PE"
		case "Settlement", "Payment":
			compKey = "Settlement"
		case "Lifecycle", "Status":
			compKey = "Order"
		case "Security", "Fraud", "AML":
			compKey = "Risk"
		case "Interface", "Connectivity":
			compKey = "Infra"
		case "Ops", "Portal":
			compKey = "FMC"
		}

		cap := capabilities[compKey]
		if cap.Status != "Supported" {
			feasibility = "Medium"
		}

		fmt.Printf("%-30s | %-12s | %-12s | %-12s | %s\n", req.Feature, feasibility, cap.Component, cap.Status, req.Description)
	}
}
